"""empty message

Revision ID: e5ce7c574ce5
Revises: 
Create Date: 2024-02-01 20:31:52.027277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ce7c574ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemonability',
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('ability_1', sa.String(length=25), nullable=False),
    sa.Column('ability_2', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('ability_id')
    )
    op.create_table('pokemonstat',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_table('pokemontype',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_1', sa.String(length=10), nullable=False),
    sa.Column('type_2', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('pokemon',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('pokemontype_id', sa.Integer(), nullable=False),
    sa.Column('pokemonstat_id', sa.Integer(), nullable=False),
    sa.Column('pokemonability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemonability_id'], ['pokemonability.ability_id'], ),
    sa.ForeignKeyConstraint(['pokemonstat_id'], ['pokemonstat.stat_id'], ),
    sa.ForeignKeyConstraint(['pokemontype_id'], ['pokemontype.type_id'], ),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    op.drop_table('pokemontype')
    op.drop_table('pokemonstat')
    op.drop_table('pokemonability')
    # ### end Alembic commands ###
